use_frameworks!

platform :ios, '9.0'

target 'LSJHImageComposeController_Example' do
  pod 'LSJHImageComposeController', :path => '../'

  target 'LSJHImageComposeController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
