use_frameworks!

platform :ios, '8.0'

target 'LSJHOptionMenu_Example' do
  pod 'LSJHOptionMenu', :path => '../'

  target 'LSJHOptionMenu_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
